# Generated by Django 6.0.5 on 2026-05-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('GYM_TRAINER', 'Gym Trainer'), ('ADMIN', 'Admin')], default='USER', max_length=20),
        ),
    ]
