# Generated by Django 6.0.5 on 2026-05-26 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_membershipplan_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='app.membershipplan'),
        ),
    ]
